<?php
/**
 * Created by PhpStorm.
 * User: Erbol
 * Date: 17.10.2016
 * Time: 18:51
 */

namespace app\behaviors;


use dektrium\user\Mailer;
use dektrium\user\models\User;
use yii\base\Behavior;
use yii\db\ActiveRecord;

class NewsBehavior extends Behavior
{
    private $_users;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $users =  User::find()->asArray()->all();
        $this->setUsers($users);
    }

    /**
     * @return mixed
     */
    public function getUsers()
    {
        return $this->_users;
    }

    /**
     * @param mixed $users
     */
    public function setUsers($users)
    {
        $this->_users = $users;
    }

    public function events()
    {
        return [
            ActiveRecord::EVENT_AFTER_INSERT => 'sendAll'
        ];
    }

    /**
     * @return mixed
     */

    public function sendAll(){
        $mailer = new Mailer();
        foreach ($this->_users as $user){
            $mailer->sendNotifyMessage($user['email'],$user['username']);
        }
    }
}